name: react-native-android-build-apk
on:
  push:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies and test
        run: |
          npm ci
          # npm test # uncomment for testing
          
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: |
         cd android && ./gradlew assembleRelease
         cd app/build/outputs/apk/release
         mv app-release.apk pokeApp.apk
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: android/app/build/outputs/apk/release/pokeApp.apk
